name: Lint and Test and Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Verify linting
        run: pnpm lint
      - name: Runing Test
        run: pnpm test
      - name: Build
        run: pnpm build
